export const UZBEKISTAN_REGIONS = [
    "Toshkent shahri",
    "Toshkent viloyati",
    "Andijon",
    "Farg'ona",
    "Namangan",
    "Samarqand",
    "Buxoro",
    "Xorazm",
    "Qashqadaryo",
    "Surxondaryo",
    "Jizzax",
    "Sirdaryo",
    "Navoiy",
    "Qoraqalpog'iston Respublikasi",
];

export const FACULTY_OPTIONS = [
    "Iqtisodiyot",
    "Moliya",
    "Buxgalteriya va audit",
    "Bank ishi",
    "Menejment",
    "Marketing",
    "Biznes boshqaruvi",
    "Axborot tizimlari va texnologiyalari",
    "Dasturiy injiniring",
    "Kompyuter injiniringi",
    "Sun'iy intellekt",
    "Matematika",
    "Fizika",
    "Kimyo",
    "Biologiya",
    "Filologiya",
    "Tarix",
    "Huquq",
    "Pedagogika",
    "Psixologiya",
    "Tibbiyot",
    "Stomatologiya",
    "Farmatsiya",
    "Arxitektura",
    "Qurilish",
    "Transport",
    "Energetika",
    "Turizm",
    "Jurnalistika",
    "Xalqaro munosabatlar",
];
