-- Stage automation triggers for bigint-based CRM tables.
-- Admins save trigger settings here; Postgres creates reminder tasks when a lead moves into a configured stage.

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  text TEXT NOT NULL,
  status BOOLEAN NOT NULL DEFAULT false,
  lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  date DATE,
  time TIME WITHOUT TIME ZONE,
  employee_id BIGINT REFERENCES xodimlar(id) ON DELETE SET NULL
);

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS task_type TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS result TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;

UPDATE tasks
SET task_type = 'qayta_aloqa'
WHERE task_type IS NULL;

UPDATE tasks
SET updated_at = COALESCE(created_at, NOW())
WHERE updated_at IS NULL;

ALTER TABLE tasks ALTER COLUMN task_type SET DEFAULT 'qayta_aloqa';
ALTER TABLE tasks ALTER COLUMN task_type SET NOT NULL;
ALTER TABLE tasks ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE tasks ALTER COLUMN updated_at SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'tasks_task_type_check'
      AND conrelid = 'tasks'::regclass
  ) THEN
    ALTER TABLE tasks
      ADD CONSTRAINT tasks_task_type_check
      CHECK (task_type IN ('qayta_aloqa', 'uchrashuv', 'eslatma', 'boshqa')) NOT VALID;
  END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_tasks_lead_id ON tasks(lead_id);
CREATE INDEX IF NOT EXISTS idx_tasks_employee_id ON tasks(employee_id);
CREATE INDEX IF NOT EXISTS idx_tasks_date ON tasks(date);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_task_type ON tasks(task_type);

ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON tasks TO authenticated;

DO $$
DECLARE
  sequence_name TEXT;
BEGIN
  sequence_name := pg_get_serial_sequence('tasks', 'id');

  IF sequence_name IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', sequence_name);
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'tasks'
      AND policyname = 'Allow authenticated users to read tasks'
  ) THEN
    CREATE POLICY "Allow authenticated users to read tasks"
      ON tasks FOR SELECT
      TO authenticated
      USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'tasks'
      AND policyname = 'Allow authenticated users to insert tasks'
  ) THEN
    CREATE POLICY "Allow authenticated users to insert tasks"
      ON tasks FOR INSERT
      TO authenticated
      WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'tasks'
      AND policyname = 'Allow authenticated users to update tasks'
  ) THEN
    CREATE POLICY "Allow authenticated users to update tasks"
      ON tasks FOR UPDATE
      TO authenticated
      USING (true)
      WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'tasks'
      AND policyname = 'Allow authenticated users to delete tasks'
  ) THEN
    CREATE POLICY "Allow authenticated users to delete tasks"
      ON tasks FOR DELETE
      TO authenticated
      USING (true);
  END IF;
END;
$$;

DROP TRIGGER IF EXISTS tasks_updated_at ON tasks;
CREATE TRIGGER tasks_updated_at
  BEFORE UPDATE ON tasks
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS stage_automation_triggers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pipeline_id UUID NOT NULL REFERENCES piplines(id) ON DELETE CASCADE,
  stage_id BIGINT NOT NULL REFERENCES stages(id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT 'Etapga o''tganda eslatma',
  event_type TEXT NOT NULL DEFAULT 'lead_entered_stage'
    CHECK (event_type IN ('lead_entered_stage')),
  action_type TEXT NOT NULL DEFAULT 'create_task'
    CHECK (action_type IN ('create_task')),
  enabled BOOLEAN NOT NULL DEFAULT true,
  delay_minutes INTEGER NOT NULL DEFAULT 0 CHECK (delay_minutes >= 0),
  schedule_timezone TEXT NOT NULL DEFAULT 'Asia/Tashkent'
    CHECK (length(trim(schedule_timezone)) > 0),
  task_text TEXT NOT NULL,
  task_type TEXT NOT NULL DEFAULT 'qayta_aloqa'
    CHECK (task_type IN ('qayta_aloqa', 'uchrashuv', 'eslatma', 'boshqa')),
  assignee_mode TEXT NOT NULL DEFAULT 'lead_employee'
    CHECK (assignee_mode IN ('lead_employee', 'current_user', 'specific_employee')),
  assignee_employee_id BIGINT REFERENCES xodimlar(id) ON DELETE SET NULL,
  created_by UUID DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT stage_automation_triggers_assignee_check
    CHECK (
      assignee_mode <> 'specific_employee'
      OR assignee_employee_id IS NOT NULL
    )
);

CREATE INDEX IF NOT EXISTS idx_stage_automation_triggers_pipeline_id
  ON stage_automation_triggers(pipeline_id);
CREATE INDEX IF NOT EXISTS idx_stage_automation_triggers_stage_id
  ON stage_automation_triggers(stage_id);
CREATE INDEX IF NOT EXISTS idx_stage_automation_triggers_enabled
  ON stage_automation_triggers(enabled);
CREATE INDEX IF NOT EXISTS idx_stage_automation_triggers_assignee_employee_id
  ON stage_automation_triggers(assignee_employee_id);

ALTER TABLE stage_automation_triggers ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON stage_automation_triggers TO authenticated;

DO $$
DECLARE
  sequence_name TEXT;
BEGIN
  sequence_name := pg_get_serial_sequence('stage_automation_triggers', 'id');

  IF sequence_name IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', sequence_name);
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'stage_automation_triggers'
      AND policyname = 'Allow authenticated users to read stage automation triggers'
  ) THEN
    CREATE POLICY "Allow authenticated users to read stage automation triggers"
      ON stage_automation_triggers FOR SELECT
      TO authenticated
      USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'stage_automation_triggers'
      AND policyname = 'Allow super-admin to insert stage automation triggers'
  ) THEN
    CREATE POLICY "Allow super-admin to insert stage automation triggers"
      ON stage_automation_triggers FOR INSERT
      TO authenticated
      WITH CHECK (
        EXISTS (
          SELECT 1 FROM xodimlar
          WHERE xodimlar.employee_id = auth.uid()::text
            AND xodimlar.role = 'super-admin'
        )
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'stage_automation_triggers'
      AND policyname = 'Allow super-admin to update stage automation triggers'
  ) THEN
    CREATE POLICY "Allow super-admin to update stage automation triggers"
      ON stage_automation_triggers FOR UPDATE
      TO authenticated
      USING (
        EXISTS (
          SELECT 1 FROM xodimlar
          WHERE xodimlar.employee_id = auth.uid()::text
            AND xodimlar.role = 'super-admin'
        )
      )
      WITH CHECK (
        EXISTS (
          SELECT 1 FROM xodimlar
          WHERE xodimlar.employee_id = auth.uid()::text
            AND xodimlar.role = 'super-admin'
        )
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'stage_automation_triggers'
      AND policyname = 'Allow super-admin to delete stage automation triggers'
  ) THEN
    CREATE POLICY "Allow super-admin to delete stage automation triggers"
      ON stage_automation_triggers FOR DELETE
      TO authenticated
      USING (
        EXISTS (
          SELECT 1 FROM xodimlar
          WHERE xodimlar.employee_id = auth.uid()::text
            AND xodimlar.role = 'super-admin'
        )
      );
  END IF;
END;
$$;

DROP TRIGGER IF EXISTS stage_automation_triggers_updated_at ON stage_automation_triggers;
CREATE TRIGGER stage_automation_triggers_updated_at
  BEFORE UPDATE ON stage_automation_triggers
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE OR REPLACE FUNCTION render_stage_automation_task_text(
  template TEXT,
  lead_name TEXT,
  stage_name TEXT
)
RETURNS TEXT AS $$
BEGIN
  RETURN REPLACE(
    REPLACE(template, '{{lead_name}}', COALESCE(lead_name, '')),
    '{{stage_name}}',
    COALESCE(stage_name, '')
  );
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION handle_lead_stage_automation_triggers()
RETURNS TRIGGER AS $$
DECLARE
  trigger_row stage_automation_triggers%ROWTYPE;
  assigned_employee_id BIGINT;
  current_employee_id BIGINT;
  new_stage_name TEXT;
  scheduled_at TIMESTAMP WITH TIME ZONE;
BEGIN
  IF OLD.stage_id IS NOT DISTINCT FROM NEW.stage_id THEN
    RETURN NEW;
  END IF;

  SELECT id
  INTO current_employee_id
  FROM xodimlar
  WHERE employee_id = auth.uid()::text
  LIMIT 1;

  SELECT name
  INTO new_stage_name
  FROM stages
  WHERE id = NEW.stage_id;

  FOR trigger_row IN
    SELECT *
    FROM stage_automation_triggers
    WHERE pipeline_id = NEW.pipeline_id
      AND stage_id = NEW.stage_id
      AND enabled = true
      AND event_type = 'lead_entered_stage'
      AND action_type = 'create_task'
    ORDER BY created_at ASC
  LOOP
    assigned_employee_id := CASE trigger_row.assignee_mode
      WHEN 'specific_employee' THEN trigger_row.assignee_employee_id
      WHEN 'current_user' THEN current_employee_id
      ELSE NEW.employee_id
    END;

    assigned_employee_id := COALESCE(
      assigned_employee_id,
      NEW.employee_id,
      current_employee_id
    );

    scheduled_at := NOW() + (trigger_row.delay_minutes * INTERVAL '1 minute');

    INSERT INTO tasks (
      text,
      status,
      lead_id,
      date,
      time,
      employee_id,
      task_type
    )
    VALUES (
      render_stage_automation_task_text(
        trigger_row.task_text,
        NEW.name,
        new_stage_name
      ),
      false,
      NEW.id,
      (scheduled_at AT TIME ZONE trigger_row.schedule_timezone)::DATE,
      (scheduled_at AT TIME ZONE trigger_row.schedule_timezone)::TIME(0),
      assigned_employee_id,
      trigger_row.task_type
    );
  END LOOP;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS leads_stage_automation_triggers ON leads;
CREATE TRIGGER leads_stage_automation_triggers
  AFTER UPDATE OF stage_id ON leads
  FOR EACH ROW
  WHEN (OLD.stage_id IS DISTINCT FROM NEW.stage_id)
  EXECUTE FUNCTION handle_lead_stage_automation_triggers();
