-- Lead timeline events for amoCRM-style activity history.
-- Stores important lead changes and task lifecycle events in one append-only feed.

CREATE OR REPLACE FUNCTION get_current_xodim_id()
RETURNS BIGINT AS $$
DECLARE
  current_xodim_id BIGINT;
BEGIN
  SELECT id
  INTO current_xodim_id
  FROM xodimlar
  WHERE employee_id::TEXT = auth.uid()::TEXT
  LIMIT 1;

  RETURN current_xodim_id;
END;
$$ LANGUAGE plpgsql STABLE;

CREATE TABLE IF NOT EXISTS lead_timeline_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  pipeline_id UUID REFERENCES piplines(id) ON DELETE SET NULL,
  stage_id BIGINT REFERENCES stages(id) ON DELETE SET NULL,
  employee_id BIGINT REFERENCES xodimlar(id) ON DELETE SET NULL,
  actor_employee_id BIGINT REFERENCES xodimlar(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'lead_timeline_events_event_type_check'
      AND conrelid = 'lead_timeline_events'::regclass
  ) THEN
    ALTER TABLE lead_timeline_events
      ADD CONSTRAINT lead_timeline_events_event_type_check
      CHECK (
        event_type IN (
          'lead_created',
          'stage_changed',
          'responsible_changed',
          'fields_changed',
          'task_created',
          'task_completed',
          'task_reopened',
          'note_added'
        )
      ) NOT VALID;
  END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_lead_timeline_events_lead_time
  ON lead_timeline_events(lead_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_lead_timeline_events_pipeline_id
  ON lead_timeline_events(pipeline_id);
CREATE INDEX IF NOT EXISTS idx_lead_timeline_events_stage_id
  ON lead_timeline_events(stage_id);
CREATE INDEX IF NOT EXISTS idx_lead_timeline_events_employee_id
  ON lead_timeline_events(employee_id);
CREATE INDEX IF NOT EXISTS idx_lead_timeline_events_actor_employee_id
  ON lead_timeline_events(actor_employee_id);
CREATE INDEX IF NOT EXISTS idx_lead_timeline_events_event_type
  ON lead_timeline_events(event_type);
CREATE INDEX IF NOT EXISTS idx_lead_timeline_events_metadata
  ON lead_timeline_events USING GIN(metadata);

ALTER TABLE lead_timeline_events ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT ON lead_timeline_events TO authenticated;

DO $$
DECLARE
  sequence_name TEXT;
BEGIN
  sequence_name := pg_get_serial_sequence('lead_timeline_events', 'id');

  IF sequence_name IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', sequence_name);
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'lead_timeline_events'
      AND policyname = 'Allow authenticated users to read lead timeline events'
  ) THEN
    CREATE POLICY "Allow authenticated users to read lead timeline events"
      ON lead_timeline_events FOR SELECT
      TO authenticated
      USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'lead_timeline_events'
      AND policyname = 'Allow authenticated users to insert lead timeline events'
  ) THEN
    CREATE POLICY "Allow authenticated users to insert lead timeline events"
      ON lead_timeline_events FOR INSERT
      TO authenticated
      WITH CHECK (true);
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION log_lead_created_timeline()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO lead_timeline_events (
    lead_id,
    pipeline_id,
    stage_id,
    employee_id,
    actor_employee_id,
    event_type,
    title,
    body,
    metadata,
    occurred_at
  )
  VALUES (
    NEW.id,
    NEW.pipeline_id,
    NEW.stage_id,
    NEW.employee_id,
    get_current_xodim_id(),
    'lead_created',
    'Lid yaratildi',
    NEW.name,
    jsonb_build_object(
      'lead_name', NEW.name,
      'phone', NEW.phone,
      'utm', NEW.utm
    ),
    COALESCE(NEW.created_at, NOW())
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION log_lead_updated_timeline()
RETURNS TRIGGER AS $$
DECLARE
  old_stage_name TEXT;
  new_stage_name TEXT;
  old_employee_name TEXT;
  new_employee_name TEXT;
  changes JSONB := '[]'::jsonb;
  actor_id BIGINT;
BEGIN
  actor_id := get_current_xodim_id();

  IF OLD.stage_id IS DISTINCT FROM NEW.stage_id THEN
    SELECT name INTO old_stage_name FROM stages WHERE id = OLD.stage_id;
    SELECT name INTO new_stage_name FROM stages WHERE id = NEW.stage_id;

    INSERT INTO lead_timeline_events (
      lead_id,
      pipeline_id,
      stage_id,
      employee_id,
      actor_employee_id,
      event_type,
      title,
      body,
      metadata,
      occurred_at
    )
    VALUES (
      NEW.id,
      NEW.pipeline_id,
      NEW.stage_id,
      NEW.employee_id,
      actor_id,
      'stage_changed',
      'Etap o''zgardi',
      COALESCE(old_stage_name, '-') || ' -> ' || COALESCE(new_stage_name, '-'),
      jsonb_build_object(
        'old_stage_id', OLD.stage_id,
        'new_stage_id', NEW.stage_id,
        'old_stage_name', old_stage_name,
        'new_stage_name', new_stage_name
      ),
      NOW()
    );
  END IF;

  IF OLD.employee_id IS DISTINCT FROM NEW.employee_id THEN
    SELECT name INTO old_employee_name FROM xodimlar WHERE id = OLD.employee_id;
    SELECT name INTO new_employee_name FROM xodimlar WHERE id = NEW.employee_id;

    INSERT INTO lead_timeline_events (
      lead_id,
      pipeline_id,
      stage_id,
      employee_id,
      actor_employee_id,
      event_type,
      title,
      body,
      metadata,
      occurred_at
    )
    VALUES (
      NEW.id,
      NEW.pipeline_id,
      NEW.stage_id,
      NEW.employee_id,
      actor_id,
      'responsible_changed',
      'Mas''ul xodim o''zgardi',
      COALESCE(old_employee_name, '-') || ' -> ' || COALESCE(new_employee_name, '-'),
      jsonb_build_object(
        'old_employee_id', OLD.employee_id,
        'new_employee_id', NEW.employee_id,
        'old_employee_name', old_employee_name,
        'new_employee_name', new_employee_name
      ),
      NOW()
    );
  END IF;

  IF OLD.name IS DISTINCT FROM NEW.name THEN
    changes := changes || jsonb_build_array(jsonb_build_object('field', 'name', 'label', 'Ism', 'old', OLD.name, 'new', NEW.name));
  END IF;

  IF OLD.phone IS DISTINCT FROM NEW.phone THEN
    changes := changes || jsonb_build_array(jsonb_build_object('field', 'phone', 'label', 'Telefon', 'old', OLD.phone, 'new', NEW.phone));
  END IF;

  IF OLD.phone_2 IS DISTINCT FROM NEW.phone_2 THEN
    changes := changes || jsonb_build_array(jsonb_build_object('field', 'phone_2', 'label', 'Qo''shimcha telefon', 'old', OLD.phone_2, 'new', NEW.phone_2));
  END IF;

  IF OLD.location IS DISTINCT FROM NEW.location THEN
    changes := changes || jsonb_build_array(jsonb_build_object('field', 'location', 'label', 'Manzil', 'old', OLD.location, 'new', NEW.location));
  END IF;

  IF OLD.age IS DISTINCT FROM NEW.age THEN
    changes := changes || jsonb_build_array(jsonb_build_object('field', 'age', 'label', 'Yosh', 'old', OLD.age, 'new', NEW.age));
  END IF;

  IF OLD.gender IS DISTINCT FROM NEW.gender THEN
    changes := changes || jsonb_build_array(jsonb_build_object('field', 'gender', 'label', 'Jinsi', 'old', OLD.gender, 'new', NEW.gender));
  END IF;

  IF OLD.date_of_year IS DISTINCT FROM NEW.date_of_year THEN
    changes := changes || jsonb_build_array(jsonb_build_object('field', 'date_of_year', 'label', 'Tug''ilgan sana', 'old', OLD.date_of_year, 'new', NEW.date_of_year));
  END IF;

  IF OLD.utm IS DISTINCT FROM NEW.utm THEN
    changes := changes || jsonb_build_array(jsonb_build_object('field', 'utm', 'label', 'UTM Source', 'old', OLD.utm, 'new', NEW.utm));
  END IF;

  IF OLD.status IS DISTINCT FROM NEW.status THEN
    changes := changes || jsonb_build_array(jsonb_build_object('field', 'status', 'label', 'Status', 'old', OLD.status, 'new', NEW.status));
  END IF;

  IF jsonb_array_length(changes) > 0 THEN
    INSERT INTO lead_timeline_events (
      lead_id,
      pipeline_id,
      stage_id,
      employee_id,
      actor_employee_id,
      event_type,
      title,
      body,
      metadata,
      occurred_at
    )
    VALUES (
      NEW.id,
      NEW.pipeline_id,
      NEW.stage_id,
      NEW.employee_id,
      actor_id,
      'fields_changed',
      'Ma''lumotlar o''zgardi',
      jsonb_array_length(changes)::TEXT || ' ta maydon yangilandi',
      jsonb_build_object('changes', changes),
      NOW()
    );
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION log_task_timeline()
RETURNS TRIGGER AS $$
DECLARE
  lead_row leads%ROWTYPE;
  task_event_type TEXT;
  task_title TEXT;
BEGIN
  SELECT *
  INTO lead_row
  FROM leads
  WHERE id = NEW.lead_id;

  IF NOT FOUND THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' THEN
    task_event_type := 'task_created';
    task_title := 'Vazifa qo''shildi';
  ELSIF TG_OP = 'UPDATE'
    AND OLD.status IS DISTINCT FROM NEW.status
    AND NEW.status = true THEN
    task_event_type := 'task_completed';
    task_title := 'Vazifa bajarildi';
  ELSIF TG_OP = 'UPDATE'
    AND OLD.status IS DISTINCT FROM NEW.status
    AND NEW.status = false THEN
    task_event_type := 'task_reopened';
    task_title := 'Vazifa qayta ochildi';
  ELSE
    RETURN NEW;
  END IF;

  INSERT INTO lead_timeline_events (
    lead_id,
    pipeline_id,
    stage_id,
    employee_id,
    actor_employee_id,
    event_type,
    title,
    body,
    metadata,
    occurred_at
  )
  VALUES (
    NEW.lead_id,
    lead_row.pipeline_id,
    lead_row.stage_id,
    NEW.employee_id,
    get_current_xodim_id(),
    task_event_type,
    task_title,
    NEW.text,
    jsonb_build_object(
      'task_id', NEW.id,
      'task_text', NEW.text,
      'task_type', NEW.task_type,
      'task_date', NEW.date,
      'task_time', NEW.time,
      'task_result', NEW.result
    ),
    NOW()
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS leads_timeline_created ON leads;
CREATE TRIGGER leads_timeline_created
  AFTER INSERT ON leads
  FOR EACH ROW
  EXECUTE FUNCTION log_lead_created_timeline();

DROP TRIGGER IF EXISTS leads_timeline_updated ON leads;
CREATE TRIGGER leads_timeline_updated
  AFTER UPDATE ON leads
  FOR EACH ROW
  WHEN (
    OLD.stage_id IS DISTINCT FROM NEW.stage_id
    OR OLD.employee_id IS DISTINCT FROM NEW.employee_id
    OR OLD.name IS DISTINCT FROM NEW.name
    OR OLD.phone IS DISTINCT FROM NEW.phone
    OR OLD.phone_2 IS DISTINCT FROM NEW.phone_2
    OR OLD.location IS DISTINCT FROM NEW.location
    OR OLD.age IS DISTINCT FROM NEW.age
    OR OLD.gender IS DISTINCT FROM NEW.gender
    OR OLD.date_of_year IS DISTINCT FROM NEW.date_of_year
    OR OLD.utm IS DISTINCT FROM NEW.utm
    OR OLD.status IS DISTINCT FROM NEW.status
  )
  EXECUTE FUNCTION log_lead_updated_timeline();

DROP TRIGGER IF EXISTS tasks_timeline_inserted ON tasks;
CREATE TRIGGER tasks_timeline_inserted
  AFTER INSERT ON tasks
  FOR EACH ROW
  EXECUTE FUNCTION log_task_timeline();

DROP TRIGGER IF EXISTS tasks_timeline_updated ON tasks;
CREATE TRIGGER tasks_timeline_updated
  AFTER UPDATE ON tasks
  FOR EACH ROW
  WHEN (OLD.status IS DISTINCT FROM NEW.status)
  EXECUTE FUNCTION log_task_timeline();

INSERT INTO lead_timeline_events (
  lead_id,
  pipeline_id,
  stage_id,
  employee_id,
  event_type,
  title,
  body,
  metadata,
  occurred_at
)
SELECT
  leads.id,
  leads.pipeline_id,
  leads.stage_id,
  leads.employee_id,
  'lead_created',
  'Lid yaratildi',
  leads.name,
  jsonb_build_object(
    'lead_name', leads.name,
    'phone', leads.phone,
    'utm', leads.utm,
    'backfilled', true
  ),
  COALESCE(leads.created_at, NOW())
FROM leads
WHERE NOT EXISTS (
  SELECT 1
  FROM lead_timeline_events
  WHERE lead_timeline_events.lead_id = leads.id
    AND lead_timeline_events.event_type = 'lead_created'
);
